### ISSUE TITLE
Shrink repo

### ISSUE THREAD

**Issue by zautumnz** [treepanel/treepanel#13]
Upstream checked in a bunch of binary blobs, including chromedriver, the selenium jar, zip files, etc. git-filter-branch or similar to get those removed

**Comment by zautumnz** [comment]
Done. https://github.com/newren/git-filter-repo/ is so much nicer than git-filter-branch. Repo size is down from about 78 mb to about 4. Anyone pointing to this remote will need to reset.

**Comment by max-hk** [comment]
@zacanger IMO, it will be better if we keep commit hashes and instead clone the repo with `--depth 1`

**Comment by zautumnz** [comment]
Good idea, I restored those commits
