### ISSUE TITLE
Renaming and/or org?

### ISSUE THREAD

**Issue by zautumnz** [treepanel/treepanel#8]
If this does become a community-maintained fork, should it live in a Github org? Should it be renamed?

**Comment by aloisdg** [comment]
+1 for moving to a GitHub Org. Not sure about the renaming but I would be fine with "Octotree Origin".

**Comment by zautumnz** [comment]
I think it would be nice to avoid the word `octotree` just so there's no confusion. Maybe something similar like ghtree or octofiles? "There are two hard problems in computer science"...

**Comment by hyiltiz** [comment]
If it is possible to make it work with Gitlab, Bitbucket, SourceHut etc., then maybe a more generic name like `TreePanel` etc. might work quite well.

**Comment by zautumnz** [comment]
I like that!
